version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
#  - package-ecosystem: "npm"
#    directory: "/app/app-web"
#    schedule:
#      interval: "daily"